### PR TITLE
Refactoring Linx duplicated types

### PR DESCRIPTION
**Pull request by Samuel-Brito19**
Working to mitigate unnecessary duplicated types on Linx related types.

### CODE REVIEW

**Comment by viktormarinho** [comment]
Once you are happy with the progress here you can tag me @Samuel-Brito19 !

Btw: I don't think you need to update the deco version, seems out of scope for this PR

**Comment by Samuel-Brito19** [comment]
Hi @viktormarinho! I did some modifications trying to solve the problem, but I have some doubts about some cases.
For example, this `Response` interface is present in 3 files but have no use in none of them. Should I take it off?

```
export interface Response {
  Errors: LinxError[];
  IsValid: boolean;
  RefreshBasket: boolean;
  ResponseCallBack: ResponseCallBack;
  SuccessMessage: null;
  Url: null;
  Warnings: unknown[];
}
```
There's other cases similar to that one. Check my changes and please give me a feedback!

**Comment by viktormarinho** [comment]
> Hi @viktormarinho! I did some modifications trying to solve the problem, but I have some doubts about some cases. For example, this `Response` interface is present in 3 files but have no use in none of them. Should I take it off?
> 
> ```
> export interface Response {
>   Errors: LinxError[];
>   IsValid: boolean;
>   RefreshBasket: boolean;
>   ResponseCallBack: ResponseCallBack;
>   SuccessMessage: null;
>   Url: null;
>   Warnings: unknown[];
> }
> ```
> 
> There's other cases similar to that one. Check my changes and please give me a feedback!

@Samuel-Brito19 If there are types without i believe you can delete them. Can you share the other cases? For the Response case it's ok.

**Review by viktormarinho — APPROVED** [review]
Really nice! 👍

**Pull request merged**
