### PR TITLE
[Shopify] - Add more information to product collections

### PR DESCRIPTION
**Pull request by vitoUwu**

### CODE REVIEW

**Comment by guitavano** [comment]
I think change "name" can broke some frontend components that already use that. Can you send an example of this extra information added?

**Comment by lucis** [comment]
@vitoUwu yes, exactly

If some frontend component, for example, does: `collections.filter(({ name }) => name === "COLLECTION"`, after this new version it will break.

What do you think about it?

**Comment by vitoUwu** [comment]
@lucis I can't think of a good solution for both sides, if I changed "name" or "value" it would break the frontends that use the current way, and I needed the tilte (name) of the collection, its handle (value) and a way to identify that the object is a collection (propertyID). Do you have any suggestions on what can be done?

**Comment by guitavano** [comment]
The most important thing is maintain current attributes.

what do you think about:

```js
{ 
"@type": "PropertyValue"
"@id": "gid/...."
name: "COLLECTION", 
value: "Lista de Bolsas",
valueReference: "listas"
}
```

**Comment by vitoUwu** [comment]
Hmm, this should work

**Comment by vitoUwu** [comment]
I kept the properties of the old object and added the new information in other properties

**Review by guitavano — APPROVED** [review]

**Pull request merged**
